version: '3.4'

services:
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - frontend
      - backend
  
  frontend:
    container_name: frontend
    build:
      context: ./webapp.frontend
      dockerfile: Dockerfile

  backend:
    container_name: backend
    build:
      context: ./webapp.backend
      dockerfile: Dockerfile
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "webapp"
      POSTGRES_PASSWORD: "webapp"
    volumes:
      - "./postgresql/data/:/var/lib/postgresql/data"