// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webapp.backend;

#nullable disable

namespace webapp.backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("webapp.backend.data.entities.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Forecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 2, 4),
                            Summary = "Mild",
                            TemperatureC = 32
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 2, 5),
                            Summary = "Bracing",
                            TemperatureC = 4
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 2, 6),
                            Summary = "Chilly",
                            TemperatureC = 42
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 2, 7),
                            Summary = "Sweltering",
                            TemperatureC = 7
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 2, 8),
                            Summary = "Warm",
                            TemperatureC = -6
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 2, 9),
                            Summary = "Chilly",
                            TemperatureC = 39
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 2, 10),
                            Summary = "Freezing",
                            TemperatureC = 7
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2024, 2, 11),
                            Summary = "Balmy",
                            TemperatureC = 39
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2024, 2, 12),
                            Summary = "Hot",
                            TemperatureC = -20
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2024, 2, 13),
                            Summary = "Freezing",
                            TemperatureC = 19
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
